spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/micro-cloud-consumer?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    druid:
      connection-init-sqls: set names utf8mb4
      initial-size: 5 #初始化大小
      min-idle: 5 # 最小
      max-active: 20 # 最大
      max-wait: 60000 # 配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true # 打开PSCache，并且指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet: # 配置DruidStatViewServlet
        url-pattern: "/druid/*"
        #allow: 127.0.0.1,192.168.163.1  # IP白名单(没有配置或者为空，则允许所有访问)
        #deny: 192.168.1.73 # IP黑名单 (存在共同时，deny优先于allow)
        reset-enable: false # 禁用HTML页面上的“Reset All”功能
        login-username: zhuhaolin # 登录名
        login-password: zhuhaolin # 登录密码
  zipkin:
    base-url: http://127.0.0.1:8003
    enabled: true
    sender:
      type: web
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  boot:
    admin:
      client:
        url: "http://127.0.0.1:8002"
        username: dabai
        password: dabai2019

ribbon:
  eager-load:
    enabled: true
    clients: micro-service-provider
  Httpclient:
    enabled: false
  OkHttp:
    enabled: true
  ReadTimeout: 50000
  ConnectTimeout: 10000

info:
  application.author: 'zhuhaolin'
  application.email: '18575624813@163.com'
  application.name: ${spring.application.name}
  application.description: '微服务: 业务服务'
  application.version: ${project.parent.version}
  company.name: 'www.zyzygame.com'

logging:
  file: /home/app/logs/${spring.application.name}/global/jingle-global.log
  level:
    com.dabai.springcloud.consumer.feign.DeptConsumerService: DEBUG

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
  compression:
    request:
      enabled: true # 配置请求GZIP压缩
      mime-types: text/xml,application/xml,application/json # 配置压缩支持的MIME TYPE
      min-request-size: 2048 # 配置压缩数据大小的下限
    response:
      enabled: true # 配置响应GZIP压缩
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    hystrix:
      stream:
        enabled: true
