spring:
  boot:
    admin:
      client:
        url: "http://127.0.0.1:8002"
        username: dabai
        password: dabai2019

logging:
  file: /home/app/logs/${spring.application.name}/global/jingle-global.log
  
management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
