spring:
  boot:
    admin:
      client:
        url: "http://127.0.0.1:8005"
        username: dabai
        password: dabai2019

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  file: /home/app/logs/${spring.application.name}/global/jingle-global.log

turbine:
  app-config: micro-service-consumer # 需要聚合的服务名称
  aggregator:
    cluster-config: "default" # 需要聚合的集群名称
  cluster-name-expression: new String('default')  # 集群名表达式
