spring:
  zipkin:
    base-url: http://127.0.0.1:8003
    enabled: true
    sender:
      type: web
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  boot:
    admin:
      client:
        url: "http://127.0.0.1:8002"
        username: dabai
        password: dabai2019

ribbon:
  eager-load:
    enabled: true
    clients: micro-service-provider
  Httpclient:
    enabled: false
  OkHttp:
    enabled: true
  ReadTimeout: 50000
  ConnectTimeout: 10000

info:
  application.author: 'zhuhaolin'
  application.email: '18575624813@163.com'
  application.name: ${spring.application.name}
  application.description: '微服务: 业务服务'
  application.version: ${project.parent.version}
  company.name: 'www.zyzygame.com'

logging:
  file: /home/app/logs/${spring.application.name}/global/jingle-global.log
  level:
    com.dabai.springcloud.consumer.feign.DeptConsumerService: DEBUG

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
  compression:
    request:
      enabled: true # 配置请求GZIP压缩
      mime-types: text/xml,application/xml,application/json # 配置压缩支持的MIME TYPE
      min-request-size: 2048 # 配置压缩数据大小的下限
    response:
      enabled: true # 配置响应GZIP压缩
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    hystrix:
      stream:
        enabled: true
