spring:
  boot:
    admin:
      client:
        url: "http://127.0.0.1:8002"
        username: dabai
        password: dabai2019

management:
  metrics:
    web:
      server:
        auto-time-requests: false
